### ISSUE TITLE
Make errors compiling Quitky

### ISSUE THREAD

**Issue by sergioad** [solus-project/quirky#24]
sergio@elementary:~/Descargas/quirky$ make
make  all-recursive
make[1]: se ingresa al directorio «/home/sergio/Descargas/quirky»
Making all in data
make[2]: se ingresa al directorio «/home/sergio/Descargas/quirky/data»
make[2]: No se hace nada para «all».
make[2]: se sale del directorio «/home/sergio/Descargas/quirky/data»
Making all in src
make[2]: se ingresa al directorio «/home/sergio/Descargas/quirky/src»
Makefile:772: atención: se imponen comandos para el objetivo «IrcConstants.c»
Makefile:738: atención: se ignoran las instrucciones viejas para el objetivo «IrcConstants.c»
Makefile:777: atención: se imponen comandos para el objetivo «IrcCore.c»
Makefile:743: atención: se ignoran las instrucciones viejas para el objetivo «IrcCore.c»
Makefile:782: atención: se imponen comandos para el objetivo «IrcParser.c»
Makefile:748: atención: se ignoran las instrucciones viejas para el objetivo «IrcParser.c»
make  all-am
make[3]: se ingresa al directorio «/home/sergio/Descargas/quirky/src»
Makefile:772: atención: se imponen comandos para el objetivo «IrcConstants.c»
Makefile:738: atención: se ignoran las instrucciones viejas para el objetivo «IrcConstants.c»
Makefile:777: atención: se imponen comandos para el objetivo «IrcCore.c»
Makefile:743: atención: se ignoran las instrucciones viejas para el objetivo «IrcCore.c»
Makefile:782: atención: se imponen comandos para el objetivo «IrcParser.c»
Makefile:748: atención: se ignoran las instrucciones viejas para el objetivo «IrcParser.c»
  VALAC    quirky_vala.stamp
IrcTextWidget.vala:273.38-273.42: error: Argument 1: Cannot pass ref argument to non-reference parameter
        buf.insert_with_tags_by_name(ref i, stamp, -1, "timestamp", "default");
                                     ^^^^^
IrcTextWidget.vala:520.42-520.47: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags_by_name(ref it, b.str, -1, "default");
                                         ^^^^^^
IrcTextWidget.vala:532.42-532.47: error: Argument 1: Cannot pass ref argument to non-reference parameter
            buf.insert_with_tags_by_name(ref it, "\n", -1, "default");
                                         ^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
make[3]: *** [quirky_vala.stamp] Error 1
make[3]: se sale del directorio «/home/sergio/Descargas/quirky/src»
make[2]: *** [all] Error 2
make[2]: se sale del directorio «/home/sergio/Descargas/quirky/src»
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio «/home/sergio/Descargas/quirky»
make: *** [all] Error 2

**Comment by ikeydoherty** [comment]
That was altered in a22ced54b20db6fd7f91a4d46dea384eec83fb23

I assume you're using old Vala/Gtk

**Comment by sergioad** [comment]
I am using elementary OS and because of that vala 0.26, the newer is the 0.28

**Comment by sergioad** [comment]
yes, it was fixed, BTW you should put the warning of the need of Vala 0.28 for compiling it

**Comment by sergioad** [comment]
@ikeydoherty this should come on the README under the IMPORTANT section maybe wwith the message "Please note that vala 0.28 is needed for compiling Quirky, older versions will fail"

**Comment by ikeydoherty** [comment]
Not really sure that's an important factor @sergioad  - every project has build dependencies of a minimum version.

**Comment by sergioad** [comment]
@ikeydoherty or maybe a dependencies list and how to install instructions on the README or something like
